export const STORIES_FETCH_INIT = "STORIES_FETCH_INIT";
export const STORIES_FETCH_SUCCESS = "STORIES_FETCH_SUCCESS";
export const STORIES_FETCH_ERROR = "STORIES_FETCH_ERROR";
export const STORIES_REMOVE = "STORIES_REMOVE";
export const SORT_SET_FIELD = "SORT_SET_FIELD";
